### ISSUE TITLE
[Need] demo for watermarking/detection.py

### ISSUE THREAD

**Issue by yeahjack** [jthickstun/watermark#5]
Dear authors,

Would you mind if sharing a demo of using functions in `detections.py` for faster detections? Thank you!

**Comment by RohithKuditipudi** [comment]
Hi - sorry for the belated reply. We use the faster version of our permutation test in `c4-experiment.py`

**Comment by RohithKuditipudi** [comment]
Marking this as resolved. Let us know if you have any follow-up questions!
